import http from 'node:http'; import fs from 'node:fs/promises'; import fssync from 'node:fs'; import path from 'node:path';
import puppeteer from 'puppeteer-core';
const APP = path.resolve('app');
const TYPES={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.bin':'application/octet-stream'};
const server=http.createServer(async(req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://x').pathname); if(rel.endsWith('/'))rel+='index.html';
 const f=path.join(APP,rel); try{const b=await fs.readFile(f); res.writeHead(200,{'content-type':TYPES[path.extname(f)]||'application/octet-stream','cache-control':'no-store'}); res.end(b);}catch{res.writeHead(404).end('nf');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}/`;
const exe=['/usr/bin/chromium','/usr/bin/google-chrome-stable'].find(p=>fssync.existsSync(p));
const browser=await puppeteer.launch({executablePath:exe,headless:'shell',args:['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage();
page.on('pageerror',e=>console.log('PAGEERROR',e.message));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
await page.setViewport({width:1366,height:860});
await page.goto(base,{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,800));
const OUT = process.argv[2] || '/tmp/shot';
await fs.mkdir(OUT,{recursive:true});
for (const vp of [{name:'desktop',width:1366,height:860,deviceScaleFactor:1},{name:'phone',width:390,height:844,deviceScaleFactor:2}]) {
  await page.setViewport(vp);
  const which = process.env.SAMPLE || 'ghaf.jpg';
  await page.evaluate(()=>{location.hash='#/';});
  await new Promise(r=>setTimeout(r,300));
  await page.evaluate((w)=>{location.hash='#/?sample='+w;}, which);
  await page.waitForFunction(()=>location.hash==='#/result',{timeout:60000});
  await new Promise(r=>setTimeout(r,1400));
  await page.screenshot({path:path.join(OUT,`result-${vp.name}.png`),fullPage:true});
  console.log('shot', vp.name);
}
await browser.close(); server.close();
